import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<html lang="uk">
      <head>
          <link
              href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@300;400;600;700&display=swap"
              rel="stylesheet"
          />
      </head>
      <body>{children}</body>
      </html>
  );
}
